# Generated by Django 2.2.1 on 2019-05-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Airplane'), (1, 'Personal Car'), (2, 'Bus'), (3, 'Train'), (4, 'Foot'), (5, 'Subway'), (6, 'Cab')]),
        ),
    ]
