# Generated by Django 2.2.1 on 2019-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodations',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accomodations',
            name='price_per_night',
            field=models.FloatField(default=0),
        ),
    ]
