# Generated by Django 2.2.1 on 2019-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20190531_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodations',
            name='accomodation_type',
            field=models.IntegerField(choices=[(0, 'Hotel'), (1, 'Hostel'), (2, 'Air BnB'), (3, 'Couchsurfing'), (4, 'Camping'), (5, 'Streets'), (6, 'Private Home')]),
        ),
    ]
