# Generated by Django 2.2.1 on 2019-05-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20190531_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='destination',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='origin',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
