# Generated by Django 2.2.1 on 2019-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190530_1225'),
        ('travels', '0003_locationpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TripJoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete='requesting_to_join', to='users.User')),
                ('trip', models.ForeignKey(on_delete='requests_to_join', to='travels.Trip')),
            ],
        ),
    ]
