# Generated by Django 2.2.1 on 2019-05-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190529_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatars',
            new_name='Avatar',
        ),
    ]
