# Generated by Django 2.2.1 on 2019-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190530_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image_name',
            field=models.CharField(default='default.png', max_length=32),
        ),
    ]
